### PR TITLE
Introduced OnProperty helper to allow mixing specs of differing types…

### PR DESCRIPTION
**Pull request by felixcollins**
… where the second type is a property on the first.

see...
http://stackoverflow.com/questions/26439718/specification-patternmultitype-composite-specifications

### CODE REVIEW

**Comment by kzu** [comment]
Is it possible to undo al the Linq. changes? If the reason was to avoid collision on Expression.Compile, it would be better to fully qualify that one call, right?

Or maybe I'm missing something totally obvious ;)

**Comment by kzu** [comment]
Also, /cc @jfromaniello who did the initial implementation to get his feedback

**Comment by felixcollins** [comment]
Yeah, sorry that was probably just Resharper...  Also I think I forgot to bring over the unit test. I originally forked and PR  on CodePlex.

**Comment by felixcollins** [comment]
I've also added this to ours to allow testing spec on a single entity in code in the same way as the classic Spec pattern.  

       public bool IsSatisfiedBy(T entity)
	{
		return ToFunc().Invoke(entity);
	}

	public Func<T, bool> ToFunc()
	{
		return Expression.Compile();
	}

Shall I chuck that in another PR?

**Comment by felixcollins** [comment]
Put in IsSatisfiedBy and reverted to the private expression backing field.

**Pull request merged**
